version: '3.8'

services:
  # Auth Service Database
  mongodb-auth:
    image: mongo:7.0
    container_name: microservices-mongodb-auth
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth-service
    volumes:
      - mongodb_auth_data:/data/db
    networks:
      - microservices-network

  # User Service Database
  mongodb-user:
    image: mongo:7.0
    container_name: microservices-mongodb-user
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user-service
    volumes:
      - mongodb_user_data:/data/db
    networks:
      - microservices-network

  # Todo Service Database
  mongodb-todo:
    image: mongo:7.0
    container_name: microservices-mongodb-todo
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo-service
    volumes:
      - mongodb_todo_data:/data/db
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: microservices-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  auth-service:
    build: ./auth-service
    container_name: microservices-auth-service
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      GRPC_PORT: 50051
      JWT_SECRET: your-super-secret-jwt-key-for-development
      MONGODB_URI: mongodb://admin:password@mongodb-auth:27017/auth-service?authSource=admin
      RABBITMQ_URL: amqp://admin:password@rabbitmq:5672
    depends_on:
      - mongodb-auth
      - rabbitmq
    networks:
      - microservices-network

  user-service:
    build: ./user-service
    container_name: microservices-user-service
    restart: unless-stopped
    ports:
      - "50052:50052"
    environment:
      GRPC_PORT: 50052
      MONGODB_URI: mongodb://admin:password@mongodb-user:27017/user-service?authSource=admin
      RABBITMQ_URL: amqp://admin:password@rabbitmq:5672
    depends_on:
      - mongodb-user
      - rabbitmq
    networks:
      - microservices-network

  todo-service:
    build: ./todo-service
    container_name: microservices-todo-service
    restart: unless-stopped
    ports:
      - "50053:50053"
    environment:
      GRPC_PORT: 50053
      MONGODB_URI: mongodb://admin:password@mongodb-todo:27017/todo-service?authSource=admin
      RABBITMQ_URL: amqp://admin:password@rabbitmq:5672
    depends_on:
      - mongodb-todo
      - rabbitmq
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    container_name: microservices-api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: auth-service:50051
      USER_SERVICE_URL: user-service:50052
      TODO_SERVICE_URL: todo-service:50053
    depends_on:
      - auth-service
      - user-service
      - todo-service
    networks:
      - microservices-network

  frontend:
    build: ./frontend
    container_name: microservices-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: /api
    depends_on:
      - api-gateway
    networks:
      - microservices-network

volumes:
  mongodb_auth_data:
  mongodb_user_data:
  mongodb_todo_data:
  rabbitmq_data:

networks:
  microservices-network:
    driver: bridge
